### ISSUE TITLE
Optional Project Name prefix for Entry

### ISSUE THREAD

**Issue by phillippbertram** [nilshohmann/toggl_import#7]
It would be nice if I can optionally enable a checkbox, which will add the project name as prefix for each entry of a day.

Example:

**[hfs]** PR 337

**Comment by nilshohmann** [comment]
Would you like to have this option in a global project list maintained over the settings popup or rather as extension in the import process when selecting the projects (and save the decision for later imports)?
Should the prefix then be the same as the project name or further configurable?

**Comment by phillippbertram** [comment]
I think

> as extension in the import process when selecting the projects (and save the decision for later imports)?

would be enough :+1
